### ISSUE TITLE
After self update, program don't want to launch

### ISSUE THREAD

**Issue by H0R1Z0N** [marcussacana/VNXTLP#2]
Hi, i downloaded the latest build, tried to launch it, it self update, then a few downloaded stuff disappear from the app folder, it try to restart but fail and according to OCR Translation, to contact a system administrator. I tried compatibility mode to w7, a w7 pc and a w10 pc, w7 in usa syslocal and w10 in jp syslocal. Tried to edit the .ini without any luck. The readme also show a "Build Fail" pix and compilation error on a compiling server. Do you think it will be fixed in the coming few month ? I would like to see if that VN could be a possible future project for my team. No need to hurry, our first project's in editing midway and the second one's in translation at 20/120 files done.

Thank you very much for your work.

**Comment by marcussacana** [comment]
isn't a bug, it's because you don't have configured the VNXTLP,
Open the Settings.ini,
set those values
```ini
Host=ftp.yourhost.com
Login=YourFtpLogin
Pass=Password
```
In the password field, put the password encoded in hex, with all bytes with a xor of 0xFF, in this example format: "8787C6"

If you don't have a ftp server, can lauch the VNXTLP without the server too, just lauch with -offline
But when you run the vnxtlp in offline the script will be encrypted (A prevention for non trustable user)
To decrypt someone that have the Admin flag in the vnxtlp enabled is needed, to set the admin flag put this in the .ini
```ini
[VNXTLP]
IsMod=VNXTLP
```
